CREATE DATABASE  {{ DB_DATABASE }};

CREATE USER {{ DB_USER }} WITH REPLICATION ENCRYPTED PASSWORD '{{ DB_PASSWORD }}';
GRANT ALL PRIVILEGES ON DATABASE {{ DB_DATABASE }} TO {{ DB_USER }};
ALTER USER postgres PASSWORD '{{ DB_PASSWORD }}';

CREATE USER {{ DB_REPL_USER }} WITH REPLICATION ENCRYPTED PASSWORD '{{ DB_REPL_PASSWORD }}';

\connect {{ DB_DATABASE }}

CREATE TABLE emails (
	id SERIAL PRIMARY KEY,
	email VARCHAR(100)
);

INSERT INTO emails (email) VALUES ('bot@telegram.org'), ('s.dolbikov@yandex.ru');

CREATE TABLE phonenumbers (
	id SERIAL PRIMARY KEY,
	phonenumber VARCHAR(100)
);

INSERT INTO phonenumbers (phonenumber) VALUES ('79001112233'), ('+79123456789');

